
export interface EvidenceItem {
  id: string;
  source: 'Reddit' | 'X' | 'G2' | 'GitHub' | 'HackerNews' | 'StackOverflow' | 'Forum' | 'Other';
  raw_text: string;
  url: string;
  created_at: string; // ISO string or relative time
  author?: string;
  context?: string; // Subreddit, thread title, etc.
  engagement?: string; // e.g. "15 likes"
}

export interface BuildImplications {
  automate: string[];
  simplify: string[];
  avoid: string[];
}

export interface FounderActionPlan {
  product_concept: string; // "Build: ..."
  target_user: string; // Who feels the pain (e.g. "Video Editor")
  target_buyer: string; // Who approves spend (e.g. "Post-Production Supervisor")
  entry_wedge: string; // "Entry Wedge: ..."
  expansion_path: string; // "Expansion: ..."
}

export interface SolutionFailure {
  tool_name: string; // "Existing Wrappers"
  attempt: string; // "Attempt to parse DOM"
  failure: string; // "Fails when class names change"
  root_cause: string; // "No stable API available"
}

export interface TagMetadata {
  tier: 1 | 2 | 3 | 4 | 5; // 5 = Highest Potential
  gap_potential_score: number; // 0-100 (Computed)
  gap_density_score: number; // 0-100 (Frequency of pain)
  saturation_score: number; // 0-100 (Higher = more saturated/solved)
  wtp_score: number; // 0-100 (Willingness to Pay / Enterprise Budget)

  evidence_volume: number;
  trend_direction: 'RISING' | 'STABLE' | 'DECLINING';
  scope_bias: 'SOLO' | 'TEAM' | 'ENTERPRISE';
  last_verified_at: string;
}

export interface Tag {
  id: string;
  name: string;
  type: 'surface' | 'workflow' | 'industry' | 'tech';
  metadata: TagMetadata;
  synonyms: string[];
  exclude_terms: string[];
  status: 'ACTIVE' | 'PROVISIONAL' | 'DEPRECATED';
  selectable: boolean; // False if metadata is missing/unverified

  // New Gap-Rich Fields
  why_gap_rich: string;
  example_complaint_queries: string[];
}

export interface ProfitPlay {
  id: string;
  title: string;
  one_liner: string;
  category: 'BASIC' | 'MEDIUM' | 'EXPERT';
  relevant_keywords: string[]; // Keywords to match with Tags
}

export interface GapScores {
  // COMPONENT RATINGS (1-10) - Generated by AI
  pain_rating: number;      // Intensity of the problem
  budget_rating: number;    // Willingness to pay / Enterprise value
  structural_rating: number; // How broken is the incumbent?

  // COMPUTED METRICS
  evidence_count: number;
  overall_score: number;    // 0-100 Weighted Algorithm

  // LABELS
  confidence_label: 'High Conviction' | 'Promising' | 'Experimental' | 'Weak';
}

export interface Gap {
  id: string;
  title: string; // Pain-first title
  chokepoint_statement: string; // One bold sentence.
  pattern_observed: string; // Neutral summary

  scores: GapScores;
  kill_switch: 'Buildable' | 'Risky' | 'Trap';

  // NEW Methodology Fields
  build_confidence: 'High' | 'Medium' | 'Experimental';
  gap_origin: 'intersection' | 'single_topic';
  dominant_topic?: string;

  when_not_to_build: string[]; // 1-3 concrete reasons to avoid
  validation_steps_7_day: string[]; // Practical validation steps
  structured_failures: SolutionFailure[]; // Rigorous failure analysis

  is_verified: boolean; // True if >=3 recent quotes AND >=2 sources
  recency_warning?: string; // Text warning if evidence is >180 days

  evidence_stack: EvidenceItem[];
  workarounds: string[];
  build_implications: BuildImplications;

  // Narrative Fields
  opportunity_unlock: string; // "What this enables"
  defensibility_moat: string; // "Why this is defensible"
  why_now_statement: string; // "Why does this gap exist NOW?" (Structural reasoning)
  action_plan: FounderActionPlan; // Strategic path

  // Metadata/Helpers
  market_surface: string;
  associated_tags: Tag[]; // All tags passed to search
  relevant_tags: string[]; // Names of tags this SPECIFIC gap matches
  causal_attribution: string;
  last_evidence_seen: string;
}

export type GapStatus = 'idle' | 'scanning' | 'analyzing' | 'complete' | 'error' | 'empty';

export interface ScanAnalysis {
  status: 'Success' | 'Saturated' | 'Unrelated' | 'Low_Signal';
  reasoning: string;
  suggested_pivot?: string;
  sub_surfaces?: string[]; // Specific high-risk areas identified during decomposition
}

export interface GapScanResult {
  gaps: Gap[];
  analysis?: ScanAnalysis;
}

export interface TagIntersectionInsight {
  insight: string;
  score: number; // 0-100
  type: 'strong' | 'weak' | 'broad' | 'niche';
}

export interface SearchState {
  tags: Tag[];
  excludedTerms: string[];
  status: GapStatus;
  error?: string;
}
// -----------------------------
// Admin Analytics Types
// -----------------------------

export interface AdminOverviewResponse {
  totalScans: number;
  totalUsers: number;
  scansByStatus: Record<string, number>;
  topProfitPlays: Array<{ profitPlay: string | null; count: number }>;
  topTags: Array<{ tag: string; count: number }>;
  trendsDailyLast30Days: Array<{ date: string; count: number }>;
  successRate: number;
}

export interface AdminScansListResponse {
  items: Array<{
    id: string;
    startedAt: string;
    finishedAt: string | null;
    status: string;
    profitPlay: string | null;
    userId: string | null;
    sessionId: string | null;
    tagsCount: number;
    tags: string[];
    durationSec: number | null;
    errorCode: string | null;
    errorMessage: string | null;
    hasResult: boolean;
  }>;
  limit: number;
}

export interface AdminTrendsResponseItem {
  date: string;
  count: number;
}
